[versions]
agp = "8.4.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeCompose = "2.8.2"
lifecycleRuntimeKtx = "2.8.0"
activityCompose = "1.9.0"
composeBom = "2024.05.00"
accompanist-pager = "0.28.0"
navigation-compose= "2.7.7"
pagingRuntimeKtx = "3.3.0"
retrofit = "2.9.0"
interceptor = "4.10.0"
hilt = "2.51"
hilt-compiler = "2.51"
coil = "2.0.0-rc01"
paging3 = "3.3.0"
gson = "2.10.1"
room = "2.6.1"
hilt-navigation-compose = "1.2.0"
mockito = "5.3.1"
kotlinx-coroutines-test = "1.8.0"
google-services="4.4.2"
firebase-bom="33.1.0"
firebase-analytics = "22.0.1"
ktlint= "12.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#Unit testing
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }


androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist-pager" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist-pager" }

#navigation
navigation-compose = {group="androidx.navigation",name="navigation-compose",version.ref="navigation-compose"}
navigation-hilt-compose = {group="androidx.hilt",name="hilt-navigation-compose",version.ref="hilt-navigation-compose"}


#Retrofit
retrofit = {group="com.squareup.retrofit2",name="retrofit",version.ref="retrofit"}
retrofit-gson-converter = {group="com.squareup.retrofit2",name="converter-gson",version.ref="retrofit"}
interceptor = {group="com.squareup.okhttp3",name="logging-interceptor",version.ref="interceptor"}

#Dagger Hilt
dagger-hilt = {group="com.google.dagger",name="hilt-android",version.ref="hilt"}
dagger-hilt-compiler = {group="com.google.dagger",name="hilt-android-compiler",version.ref="hilt-compiler"}

#Coil
coil-compose = {group="io.coil-kt",name="coil-compose",version.ref="coil"}

#Paging 3
paging-compose = {group="androidx.paging",name="paging-compose",version.ref="paging3"}

#gson
gson = {group="com.google.code.gson",name="gson",version.ref="gson"}

#Room
room = {group="androidx.room",name="room-runtime",version.ref="room"}
room-compiler = {group="androidx.room",name="room-compiler",version.ref="room"}
room-paging = {group="androidx.room",name="room-paging",version.ref="room"}
room-ktx = {group="androidx.room",name="room-ktx",version.ref="room"}

firebase-bom = {group="com.google.firebase",name="firebase-bom",version.ref="firebase-bom"}
firebase-analytics = {group="com.google.firebase",name="firebase-analytics",version.ref="firebase-analytics"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerhilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }




